name: Orbit
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - shapely
  - pyproj
  - openpyxl
  - lxml
  - tqdm
  - pyvista
  - pyvistaqt
  - qtpy
  - matplotlib-base
  - pip
  - pip:
      - opencv-python-headless
      - mkl
      - shiboken6==6.7.3
      - PySide6-Essentials==6.7.3
      - PySide6-Addons==6.7.3
      - PySide6==6.7.3