name: OrbitX
channels:
  - conda-forge
  - defaults
dependencies:
  - altgraph=0.17.4
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - colorama=0.4.6
  - comm=0.2.2
  - cpython=3.11.13
  - debugpy=1.8.14
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.1
  - future=1.0.0
  - importlib-metadata=8.7.0
  - ipykernel=6.29.5
  - ipython=9.3.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - krb5=1.21.3
  - libexpat=2.7.1
  - libffi=3.4.4
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - nest-asyncio=1.6.0
  - openssl=3.5.2
  - packaging=25.0
  - parso=0.8.4
  - pefile=2023.2.7
  - pickleshare=0.7.5
  - pip=25.1
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - pyinstaller=6.15.0
  - pyinstaller-hooks-contrib=2025.8
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python_abi=3.11
  - pywin32=307
  - pywin32-ctypes=0.2.3
  - pyzmq=27.0.0
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.14.0
  - ucrt=10.0.22621.0
  - vc=14.42
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.8.1
  - xz-tools=5.8.1
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - pip:
      - beautifulsoup4==4.13.4
      - branca==0.8.1
      - certifi==2025.6.15
      - charset-normalizer==3.4.2
      - contourpy==1.3.2
      - cycler==0.12.1
      - elementpath==5.0.1
      - et-xmlfile==2.0.0
      - filelock==3.18.0
      - folium==0.20.0
      - fonttools==4.58.4
      - fsspec==2025.7.0
      - gdown==5.2.0
      - geometry==0.0.23
      - geopandas==1.1.0
      - idna==3.10
      - jinja2==3.1.6
      - kiwisolver==1.4.8
      - leaflet==0.0.3
      - lxml==5.4.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mpmath==1.3.0
      - networkx==3.5
      - numpy==2.3.0
      - opencv-python==4.11.0.86
      - openpyxl==3.1.5
      - pandas==2.3.0
      - pillow==11.2.1
      - pooch==1.8.2
      - py-cpuinfo==9.0.0
      - pycocotools==2.0.10
      - pyogrio==0.11.0
      - pyparsing==3.2.3
      - pyproj==3.7.1
      - pyside6==6.9.1
      - pyside6-addons==6.9.1
      - pyside6-essentials==6.9.1
      - pysocks==1.7.1
      - pytz==2025.2
      - pyvista==0.45.2
      - pyvistaqt==0.11.2
      - pyyaml==6.0.2
      - qtpy==2.4.3
      - requests==2.32.4
      - scipy==1.15.3
      - scooby==0.10.1
      - shapely==2.1.1
      - shiboken6==6.9.1
      - soupsieve==2.7
      - sympy==1.14.0
      - torch==2.8.0
      - torchvision==0.23.0
      - tqdm==4.67.1
      - tzdata==2025.2
      - ultralytics==8.3.177
      - ultralytics-thop==2.0.15
      - urllib3==2.4.0
      - v==1
      - vtk==9.4.2
      - xyzservices==2025.4.0
