@echo off
setlocal EnableExtensions
REM Auto-generated by ORBIT Save Project
set "CONDA_ENV=OrbitClone"
set "CONDA_ENV_FALLBACK="
if /I "%CONDA_ENV%"=="Orbit" set "CONDA_ENV_FALLBACK=OrbitClone"
if /I "%CONDA_ENV%"=="OrbitClone" set "CONDA_ENV_FALLBACK=Orbit"
set "ORBIT_SCRIPT=C:\Code\_Orbitv1.2.0\ORBITv01.2.0.py"
set "STATE_FILE=C:\Code\_Orbitv1.2.0\02_FlightRoutes\2023-11_Bierstalbrug\01_Input\complete_program_state.json"
cd /d "C:\Code\_Orbitv1.2.0"
set "CONDA_CMD="
if defined CONDA_EXE if exist "%CONDA_EXE%" set "CONDA_CMD=%CONDA_EXE%"
if not defined CONDA_CMD for %%I in (conda.bat conda.exe) do (
  for /f "delims=" %%P in ('where %%I 2^>nul') do if not defined CONDA_CMD set "CONDA_CMD=%%P"
)
if not defined CONDA_CMD for %%P in (
  "%USERPROFILE%\anaconda3\condabin\conda.bat"
  "%USERPROFILE%\miniconda3\condabin\conda.bat"
  "C:\ProgramData\Anaconda3\condabin\conda.bat"
  "C:\ProgramData\miniconda3\condabin\conda.bat"
) do if exist %%~P if not defined CONDA_CMD set "CONDA_CMD=%%~P"
if not defined CONDA_CMD (
  echo [ERROR] Conda was not found.
  echo Open an Anaconda Prompt or install Conda and try again.
  pause
  exit /b 1
)
"%CONDA_CMD%" run -n "%CONDA_ENV%" python "%ORBIT_SCRIPT%" --load "%STATE_FILE%"
if errorlevel 1 if defined CONDA_ENV_FALLBACK (
  echo [INFO] Primary env "%CONDA_ENV%" failed. Trying fallback "%CONDA_ENV_FALLBACK%"...
  "%CONDA_CMD%" run -n "%CONDA_ENV_FALLBACK%" python "%ORBIT_SCRIPT%" --load "%STATE_FILE%"
)
if errorlevel 1 (
  echo [ERROR] Failed to start with conda environment "%CONDA_ENV%".
  if defined CONDA_ENV_FALLBACK echo [ERROR] Fallback "%CONDA_ENV_FALLBACK%" also failed.
  echo Verify with: conda env list
  pause
  exit /b 1
)
